services:
  - type: worker
    name: ai-medicine-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m bot.main"
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: MODEL_NAME
        value: "llama3-8b-8192"
