services:
  - type: worker
    name: ai-med-chat-bot
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m bot.main"
    autoDeploy: true
